config/routes.rb
Rails.application.routes.draw do
  resources :peliculasses
  resources :peliculas_ls

end

app/models/peliculas_l.rb
class PeliculasL < ActiveRecord::Base
end

app/models/peliculass.rb
class Peliculass < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/peliculas_ls_controller.rb
class PeliculasLsController < ApplicationController
  before_action :set_peliculas_l, only: [:show, :edit, :update, :destroy]

  # GET /peliculas_ls
  # GET /peliculas_ls.json
  def index
    @peliculas_ls = PeliculasL.all
  end

  # GET /peliculas_ls/1
  # GET /peliculas_ls/1.json
  def show
  end

  # GET /peliculas_ls/new
  def new
    @peliculas_l = PeliculasL.new
  end

  # GET /peliculas_ls/1/edit
  def edit
  end

  # POST /peliculas_ls
  # POST /peliculas_ls.json
  def create
    @peliculas_l = PeliculasL.new(peliculas_l_params)

    respond_to do |format|
      if @peliculas_l.save
        format.html { redirect_to @peliculas_l, notice: 'Peliculas l was successfully created.' }
        format.json { render :show, status: :created, location: @peliculas_l }
      else
        format.html { render :new }
        format.json { render json: @peliculas_l.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peliculas_ls/1
  # PATCH/PUT /peliculas_ls/1.json
  def update
    respond_to do |format|
      if @peliculas_l.update(peliculas_l_params)
        format.html { redirect_to @peliculas_l, notice: 'Peliculas l was successfully updated.' }
        format.json { render :show, status: :ok, location: @peliculas_l }
      else
        format.html { render :edit }
        format.json { render json: @peliculas_l.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peliculas_ls/1
  # DELETE /peliculas_ls/1.json
  def destroy
    @peliculas_l.destroy
    respond_to do |format|
      format.html { redirect_to peliculas_ls_url, notice: 'Peliculas l was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peliculas_l
      @peliculas_l = PeliculasL.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peliculas_l_params
      params.require(:peliculas_l).permit(:Nombredepel)
    end
end

app/controllers/peliculasses_controller.rb
class PeliculassesController < ApplicationController
  before_action :set_peliculass, only: [:show, :edit, :update, :destroy]

  # GET /peliculasses
  # GET /peliculasses.json
  def index
    @peliculasses = Peliculass.all
  end

  # GET /peliculasses/1
  # GET /peliculasses/1.json
  def show
  end

  # GET /peliculasses/new
  def new
    @peliculass = Peliculass.new
  end

  # GET /peliculasses/1/edit
  def edit
  end

  # POST /peliculasses
  # POST /peliculasses.json
  def create
    @peliculass = Peliculass.new(peliculass_params)

    respond_to do |format|
      if @peliculass.save
        format.html { redirect_to @peliculass, notice: 'Peliculass was successfully created.' }
        format.json { render :show, status: :created, location: @peliculass }
      else
        format.html { render :new }
        format.json { render json: @peliculass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peliculasses/1
  # PATCH/PUT /peliculasses/1.json
  def update
    respond_to do |format|
      if @peliculass.update(peliculass_params)
        format.html { redirect_to @peliculass, notice: 'Peliculass was successfully updated.' }
        format.json { render :show, status: :ok, location: @peliculass }
      else
        format.html { render :edit }
        format.json { render json: @peliculass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peliculasses/1
  # DELETE /peliculasses/1.json
  def destroy
    @peliculass.destroy
    respond_to do |format|
      format.html { redirect_to peliculasses_url, notice: 'Peliculass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peliculass
      @peliculass = Peliculass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peliculass_params
      params.require(:peliculass).permit(:NombredePeliculas, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peliculas_ls_helper.rb
module PeliculasLsHelper
end

app/helpers/peliculasses_helper.rb
module PeliculassesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peliculas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/peliculas_ls/_form.html.erb
<%= form_for(@peliculas_l) do |f| %>
  <% if @peliculas_l.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peliculas_l.errors.count, "error") %> prohibited this peliculas_l from being saved:</h2>

      <ul>
      <% @peliculas_l.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombredepel %><br>
    <%= f.text_field :Nombredepel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peliculas_ls/edit.html.erb
<h1>Editing Peliculas L</h1>

<%= render 'form' %>

<%= link_to 'Show', @peliculas_l %> |
<%= link_to 'Back', peliculas_ls_path %>

app/views/peliculas_ls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Peliculas Ls</h1>

<table>
  <thead>
    <tr>
      <th>Nombredepel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peliculas_ls.each do |peliculas_l| %>
      <tr>
        <td><%= peliculas_l.Nombredepel %></td>
        <td><%= link_to 'Show', peliculas_l %></td>
        <td><%= link_to 'Edit', edit_peliculas_l_path(peliculas_l) %></td>
        <td><%= link_to 'Destroy', peliculas_l, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peliculas l', new_peliculas_l_path %>

app/views/peliculas_ls/new.html.erb
<h1>New Peliculas L</h1>

<%= render 'form' %>

<%= link_to 'Back', peliculas_ls_path %>

app/views/peliculas_ls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombredepel:</strong>
  <%= @peliculas_l.Nombredepel %>
</p>

<%= link_to 'Edit', edit_peliculas_l_path(@peliculas_l) %> |
<%= link_to 'Back', peliculas_ls_path %>

app/views/peliculasses/_form.html.erb
<%= form_for(@peliculass) do |f| %>
  <% if @peliculass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peliculass.errors.count, "error") %> prohibited this peliculass from being saved:</h2>

      <ul>
      <% @peliculass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :NombredePeliculas %><br>
    <%= f.text_area :NombredePeliculas %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.number_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peliculasses/edit.html.erb
<h1>Editing Peliculass</h1>

<%= render 'form' %>

<%= link_to 'Show', @peliculass %> |
<%= link_to 'Back', peliculasses_path %>

app/views/peliculasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Peliculasses</h1>

<table>
  <thead>
    <tr>
      <th>Nombredepeliculas</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peliculasses.each do |peliculass| %>
      <tr>
        <td><%= peliculass.NombredePeliculas %></td>
        <td><%= peliculass.rate %></td>
        <td><%= link_to 'Show', peliculass %></td>
        <td><%= link_to 'Edit', edit_peliculass_path(peliculass) %></td>
        <td><%= link_to 'Destroy', peliculass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peliculass', new_peliculass_path %>

app/views/peliculasses/new.html.erb
<h1>New Peliculass</h1>

<%= render 'form' %>

<%= link_to 'Back', peliculasses_path %>

app/views/peliculasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombredepeliculas:</strong>
  <%= @peliculass.NombredePeliculas %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @peliculass.rate %>
</p>

<%= link_to 'Edit', edit_peliculass_path(@peliculass) %> |
<%= link_to 'Back', peliculasses_path %>